### ISSUE TITLE
Drop `:init` from `:binding-init`?

### ISSUE THREAD

**Issue by jonase** [frenchy64/analyze#13]
Currently the `:init` key is dublicated in both `:local-binding` and `:binding-init`. Furthermore, since `:init` is included as part of `:children` in both, it complicates code walking (the same node is visited multiple times). 

I see two possible solutions:
- drop `:init` in `:binding-init`
- drop `:binding-init` altogether.

Currently I’d prefer the latter. AFAICT `:binding-init` doesnt really do anything useful and it is not an expression in `Compiler.java` so I don’t think we would loose much by delegating directly to `:local-binding`.

**Comment by jonase** [comment]
There's a lot to think about when it comes to local bindings in analyze. I think we should carefully consider how and why things are done as they are. For example, 
- I think :local-binding-expr shouldn't have :children
- :local-binding and :binding-init should not be expressions (as in the compiler)
- Instead, the binding forms (:let :letfn :fn-method) should figure out who the :children are.

**Comment by frenchy64** [comment]
I put little thought into the treatment of locals, it was really a direct port. Definitely some unneeded redundancy around the place.

Have you come across examples where you are hindered by the current code? Some short examples where these improvements are obvious would be nice.

**Comment by jonase** [comment]
One quick example (I might come up with more when I get home from work):

If we walk over the children in the expression below and (for example) warn on reflection

```
(defn f [obj]
  (let [x (.someMethod obj)]
    x))
```

How many times would the warning appear? Currently, at least 3 times.

**Comment by frenchy64** [comment]
I see.

One idea would be to rename :chidren to :init for :local-binding-expr. https://github.com/frenchy64/analyze/blob/master/src/analyze/core.clj#L119

I don't think we want to get rid of it. Needs a bit more thought.

**Comment by jonase** [comment]
> One idea would be to rename :chidren to :init for :local-binding-expr.

`:local-binding-expr` contains `:local-binding`, which contains `:init`. So when you encounter a `:local-binding-expr` you could simply do 

```
(:init (:local-binding expr))
```

> Needs a bit more thought.

I agree.

**Comment by jonase** [comment]
I'm experimenting with redesigning locals-handling in [this branch](https://github.com/jonase/analyze/tree/locals). If you're interested I'll be happy to explain/defend the rationale for the changes I've made. There are probably still bugs there and I've yet to try it out on larger code-bases.

The changes I've currently made:
- Removed MM for LocalBinding BindingInit and FnMethod. Note: these are not Expr in the compiler either.
- Removed `:op` keý from `:local-binding`, `:binding-init` and `:fn-method` as they no longer are consider "expressions" and should never appear as-is in any `:children` sequence.
- The `:children` sequence for `:fn-expr`, `:letfn` and `:let` are a bit more complicated but I think they do the right thing.

All feedback welcome.
