### ISSUE TITLE
analyze doesn't bind *ns*

### ISSUE THREAD

**Issue by arohner** [frenchy64/analyze#18]
I tried to analyze a ns that does (:require [foo.bar] :refer (baz)]), and analyze failed at the first usage of baz. 

Binding _ns_ to the namespace being analyzed solved everything. See https://gist.github.com/4534779

Edit: (clojure 1.4, analyze 0.2.5)

**Comment by frenchy64** [comment]
I'm not ignoring this, just a bit busy to look at this at the moment. Patch welcome.

**Comment by frenchy64** [comment]
I don't believe this is as simple as it seems.

Right now, `analyze-one` just calls `clojure.lang.Compiler/analyze`, which does not "compile" the code normally.

Hypothesis: For `require` and `refer` to be correctly called, `analyze-one` needs to compile each form like `clojure.lang.Compiler/compile1`, but still return analysis results.

This involves copying `c.l.C/compile` and `c.l.C/compile1` exactly, and retaining the results of calling `c.l.C/analyze`.
