### ISSUE TITLE
map->form is missing a method for :the-var

### ISSUE THREAD

**Issue by hugoduncan** [frenchy64/analyze#19]
I'm not sure about the distinction between `:var` and `:the-var`.  It seems they should have the same output?

**Comment by hugoduncan** [comment]
Thanks!

Also missing `:case*`. `:set` uses `:keyvals` instead of `:keys`. `:constant` should quote symbols (including those inside a vector).

**Comment by frenchy64** [comment]
`:case*` isn't quite right actually, the keys of the 5th argument to `case*` should be a hash.
